-- MySQL Script generated by MySQL Workbench
-- Wed Feb 12 17:34:12 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema urban_routes
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `urban_routes` ;

-- -----------------------------------------------------
-- Schema urban_routes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `urban_routes` ;
USE `urban_routes` ;



-- -----------------------------------------------------
-- Table `cat_type_of_transport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cat_type_of_transport` ;
CREATE TABLE IF NOT EXISTS `cat_type_of_transport` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `imagen` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



-- -----------------------------------------------------
-- Table `cat_line_of_transport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cat_line_of_transport` ;
CREATE TABLE IF NOT EXISTS `cat_line_of_transport` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `complete_name` VARCHAR(150) NOT NULL,
  `imagen` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



-- -----------------------------------------------------
-- Table `cat_municipalities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cat_municipalities` ;
CREATE TABLE IF NOT EXISTS `cat_municipalities` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



-- -----------------------------------------------------
-- Table `cat_faculty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cat_faculty` ;
CREATE TABLE IF NOT EXISTS `cat_faculty` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `acronym` VARCHAR(30) NOT NULL,
  `name` VARCHAR(90) NOT NULL,
  `latitude` VARCHAR(30) NOT NULL,
  `longitude` VARCHAR(30) NOT NULL,
  `is_active` ENUM('0','1') NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



-- -----------------------------------------------------
-- Table `cat_degree`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cat_degree` ;
CREATE TABLE IF NOT EXISTS `cat_degree` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_faculty` INT UNSIGNED NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `is_active` ENUM('0','1') NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  CONSTRAINT `fx_id_faculty`
    FOREIGN KEY (`id_faculty`)
    REFERENCES `cat_faculty` (`id`)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



-- -----------------------------------------------------
-- Table `transport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `transport` ;
CREATE TABLE IF NOT EXISTS `transport` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_type_of_transport` INT UNSIGNED NOT NULL,
  `id_line_of_transport` INT UNSIGNED NOT NULL,
  `frequency` VARCHAR(15) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `imagen` VARCHAR(30) NOT NULL,
  `origin` VARCHAR(20) NULL DEFAULT NULL,
  `destination` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id`),
  KEY `id_type_of_transport_idx` (`id_type_of_transport`),
  CONSTRAINT `type_of_transport_fk`
    FOREIGN KEY (`id_type_of_transport`)
    REFERENCES `cat_type_of_transport` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `line_of_transport_fk`
    FOREIGN KEY (`id_line_of_transport`)
    REFERENCES `cat_line_of_transport` (`id`)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;
CREATE TABLE IF NOT EXISTS `user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `imagen` VARCHAR(30) NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  `reference` VARCHAR(30) NOT NULL,
  `is_active` ENUM('0','1') NOT NULL DEFAULT '1',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- -----------------------------------------------------
-- Table `commentary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `commentary` ;
CREATE TABLE IF NOT EXISTS `commentary` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_user` INT UNSIGNED NOT NULL,
  `id_transport` INT UNSIGNED NOT NULL,
  `comment` VARCHAR(255) NOT NULL,
  `is_banned` INT NULL DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id`),
  CONSTRAINT `user_commentary_fx`
    FOREIGN KEY (`id_user`)
    REFERENCES `user` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `transport_commentary_fx`
    FOREIGN KEY (`id_transport`)
    REFERENCES `transport` (`id`)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- -----------------------------------------------------
-- Table `calification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `calification` ;
CREATE TABLE IF NOT EXISTS `calification` (
  `id_user` INT UNSIGNED NOT NULL,
  `id_transport` INT UNSIGNED NOT NULL,
  `calification` INT CHECK (calification >= 1 AND calification <= 5) NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `user_calification_fx`
    FOREIGN KEY (`id_user`)
    REFERENCES `user` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `transport_calification_fx`
    FOREIGN KEY (`id_transport`)
    REFERENCES `transport` (`id`)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- -----------------------------------------------------
-- Table `stop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stop` ;
CREATE TABLE IF NOT EXISTS `stop` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_municipalities` INT UNSIGNED NOT NULL,
  `latitude` VARCHAR(30) NOT NULL,
  `longitude` VARCHAR(30) NOT NULL,
  `name` VARCHAR(60) NULL DEFAULT NULL,
  `imagen` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  CONSTRAINT `id_municipalities_fk`
    FOREIGN KEY (`id_municipalities`)
    REFERENCES `cat_municipalities` (`id`)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



-- -----------------------------------------------------
-- Table `transport_stop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `transport_stop` ;
CREATE TABLE IF NOT EXISTS `transport_stop` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_transport` INT UNSIGNED NOT NULL,
  `id_stop` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  KEY `id_transport_idx` (`id_transport`),
  KEY `id_stop_idx` (`id_stop`),
  CONSTRAINT `transport_stop_transport_fk`
    FOREIGN KEY (`id_transport`)
    REFERENCES `transport` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `transport_stop_stop_fk`
    FOREIGN KEY (`id_stop`)
    REFERENCES `stop` (`id`)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



-- -----------------------------------------------------
-- Table `route_coordinates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `route_coordinates` ;
CREATE TABLE IF NOT EXISTS `route_coordinates` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_transport` INT UNSIGNED NOT NULL,
  `latitude` VARCHAR(30) NOT NULL,
  `longitude` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  CONSTRAINT `routes_cordinates_transport_fk`
    FOREIGN KEY (`id_transport`)
    REFERENCES `transport` (`id`)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



-- -----------------------------------------------------
-- Table `stop_routes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stop_routes` ;
CREATE TABLE IF NOT EXISTS `stop_routes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `stop_id_from` INT UNSIGNED NOT NULL,
  `stop_id_to` INT UNSIGNED NOT NULL,
  `distance` INT NOT NULL,
  `time` INT NOT NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  CONSTRAINT `stop_routes_stop_from_fx`
    FOREIGN KEY (`stop_id_from`)
    REFERENCES `stop` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `stop_routes_stop_to_fx`
    FOREIGN KEY (`stop_id_to`)
    REFERENCES `stop` (`id`)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
